// flow.cjs — context-scoped vertical rhythm (prose / product / compact)
//
// One class per context (e.g. `flow-prose`); no separate `.flow` root needed.
// :is() (not :where()) so the context class contributes (0,1,0) specificity and
// beats element resets like `p { margin: 0 }`.
//
// The `:not(.sr-only, [hidden], template)` guard excludes visually-collapsed or
// non-rendered siblings from the owl axis, so a conditionally-rendered or sr-only
// first child (e.g. an sr-only <h3> in a no-title state) does not inject a phantom
// gap or double up with a component's explicit margins. Applied to BOTH ends of the
// owl pair: a collapsed element never receives a margin and is never the thing a
// real element couples to.
//
// Selector keys are written out in full (no computed keys) so the file is safe
// whether the build executes or statically parses it. Later keys win at equal
// specificity — ordering is load-bearing.
//
// EVERY rule is ROOTED at the element declaring the context: a child combinator
// immediately after the :is() group, no exceptions. A descendant combinator there
// reaches arbitrary depth — through `not-prose`, through a nested context, into any
// component — and cannot be overridden by the component author, since the rule
// computes to (0,1,3) and the obvious `[&>li+li]:mt-0` only reaches (0,1,2). That
// was the footnote ghost-margin bug. The list rules keep a descendant reach WITHIN
// a list that is itself a direct child of the flow root, so nested lists retain
// their rhythm without reaching into components. Guarded by regen_spec.py check.

module.exports = {
	// No context variable blocks here. The ramp's values live in
	// styles/flow.css (generated by `custom/flow` from the Figma semantic-flow
	// tokens), which every consuming app imports — it emits the flat
	// `--flow-{context}-{rung}` source vars AND the `.flow-{context}` blocks
	// that map them onto `--flow-tight|default|loose|section`. Restating them
	// here would be a second, silently-driftable declaration of one ramp.
	// Values live in flow.css; behaviour lives here.

	// 1 · base — every VISIBLE sibling gets the default gap
	':is(.flow-prose, .flow-product, .flow-compact) > :not(.sr-only, [hidden], template) + :not(.sr-only, [hidden], template, [class*="mt-flow-"])':
		{
			marginTop: 'var(--flow-default)'
		},

	// 2 · block objects set off — loose above and below
	//
	// `.chart` here is deliberate and sits alongside figure/img/table/pre/blockquote:
	// it marks an element that should be set off with loose spacing above and below in
	// a flow. That the same word also names a typography context (contexts.cjs) is
	// overlap, not a collision — a chart in prose legitimately wants both chart
	// typography and generous surrounding space, and the two systems compose. Do not
	// rename it; this has been reported as a bug once already.
	':is(.flow-prose, .flow-product, .flow-compact) > :not(.sr-only, [hidden], template) + :is(figure, img, table, pre, blockquote, .chart):not([class*="mt-flow-"])':
		{
			marginTop: 'var(--flow-loose)'
		},
	':is(.flow-prose, .flow-product, .flow-compact) > :is(figure, img, table, pre, blockquote, .chart) + :not(.sr-only, [hidden], template, [class*="mt-flow-"])':
		{
			marginTop: 'var(--flow-loose)'
		},

	// 3 · space BEFORE headings — major vs minor (main rhythm lever)
	':is(.flow-prose, .flow-product, .flow-compact) > :not(.sr-only, [hidden], template) + :is(h1, h2, .title-1, .title-2):not([class*="mt-flow-"])':
		{
			marginTop: 'var(--flow-section)'
		},
	':is(.flow-prose, .flow-product, .flow-compact) > :not(.sr-only, [hidden], template) + :is(h3, h4, .title-3, .title-4):not([class*="mt-flow-"])':
		{
			marginTop: 'var(--flow-loose)'
		},

	// 4 · stacked headings group tightly (wins over rule 3 for consecutive headings)
	':is(.flow-prose, .flow-product, .flow-compact) > :is(h1, h2, h3, h4, [class*="title-"]) + :is(h1, h2, h3, h4, [class*="title-"]):not([class*="mt-flow-"])':
		{
			marginTop: 'var(--flow-tight)'
		},

	// 4b · companion roles couple tight to their titling primary.
	// A subhead/subtitle is a supporting line bound *beneath* its heading; an
	// eyebrow is an overline bound *above* the heading it introduces. These are
	// coupling (flow-tight), not block-to-block rhythm. Placed after rules 1 & 3
	// so they win at equal specificity for the pairings they target.

	// supporting line directly under a heading hugs it
	':is(.flow-prose, .flow-product, .flow-compact) > :is(h1, h2, h3, h4, [class*="title-"], .display, .headline, .page-head, .section-head) + :is(.subtitle, .subhead):not([class*="mt-flow-"])':
		{
			marginTop: 'var(--flow-tight)'
		},

	// eyebrow overline hugs the heading directly below it (overrides rule 3's section gap)
	':is(.flow-prose, .flow-product, .flow-compact) > .eyebrow + :is(h1, h2, h3, h4, [class*="title-"], .display, .headline, .page-head, .section-head):not([class*="mt-flow-"])':
		{
			marginTop: 'var(--flow-tight)'
		},

	// the major break sits ABOVE an eyebrow that introduces a heading — the eyebrow
	// is the top of the titling cluster, so the section gap belongs before it
	':is(.flow-prose, .flow-product, .flow-compact) > :not(.sr-only, [hidden], template) + .eyebrow:not([class*="mt-flow-"]):has(+ :is(h1, h2, .title-1, .title-2, .display, .headline, .page-head, .section-head))':
		{
			marginTop: 'var(--flow-section)'
		},

	// 5 · caption binds to its figure
	':is(.flow-prose, .flow-product, .flow-compact) > figure > figcaption': {
		marginTop: 'var(--flow-tight)'
	},

	// 6 · list internal rhythm — li is not a flow-root child, so the owl never reached
	// it. Reach is bounded to lists that are themselves direct children of the flow
	// root; a list inside a component declares its own spacing (e.g. `gap-1`).
	':is(.flow-prose, .flow-product, .flow-compact) > :is(ul, ol) li + li': {
		marginTop: 'var(--flow-tight)'
	},
	':is(.flow-prose, .flow-product, .flow-compact) > :is(ul, ol) li > :is(ul, ol)': {
		marginTop: 'var(--flow-tight)'
	},

	// 6b · description lists — definition binds to its term; pairs separate
	':is(.flow-prose, .flow-product, .flow-compact) > dl > dd': {
		marginTop: 'var(--flow-tight)'
	},
	':is(.flow-prose, .flow-product, .flow-compact) > dl > dt': {
		marginTop: 'var(--flow-default)'
	},
	':is(.flow-prose, .flow-product, .flow-compact) > dl > dt:first-child': {
		marginTop: '0'
	}

	// Optional — bind heading→body harder if minor headings read unbound:
	// ':is(.flow-prose, .flow-product, .flow-compact) > :is(h1, h2, h3, h4, [class*="title-"]) + :not(.sr-only, [hidden], template)': {
	// 	marginTop: 'var(--flow-tight)'
	// }
};
