import { scaleOrdinal, scaleSequential, scaleThreshold } from 'd3-scale';
import { interpolateViridis } from 'd3-scale-chromatic';
import { describe, expect, it } from 'vitest';
import { render } from 'vitest-browser-svelte';
import { page } from 'vitest/browser';
import ColorLegend from './ColorLegend.svelte';

// `color` scale objects taken/adapted from ColorLegend.stories.svelte.
const bandColorScale = scaleThreshold(
	[22, 35, 51, 72],
	['#c5dcf2', '#8fb4db', '#628dba', '#3b6894', '#18446c']
);

const ordinalScale = scaleOrdinal(
	['A', 'B', 'C', 'D'],
	['#c5dcf2', '#8fb4db', '#628dba', '#3b6894']
);

const sequentialScale = scaleSequential([0, 100], interpolateViridis);

describe('ColorLegend', () => {
	describe('threshold (categorical) scale', () => {
		it('renders one swatch rect per range color, in range order', async () => {
			const { container } = render(ColorLegend, {
				color: bandColorScale,
				title: 'Age (years)'
			});

			const rects = container.querySelectorAll('svg > g > rect');
			expect(rects).toHaveLength(5);

			expect(rects[0]).toHaveAttribute('fill', '#c5dcf2');
			expect(rects[1]).toHaveAttribute('fill', '#8fb4db');
			expect(rects[2]).toHaveAttribute('fill', '#628dba');
			expect(rects[3]).toHaveAttribute('fill', '#3b6894');
			expect(rects[4]).toHaveAttribute('fill', '#18446c');

			// x position should increase left-to-right, matching the range order.
			const xPositions = Array.from(rects).map((r) => Number(r.getAttribute('x')));
			expect(xPositions).toEqual([...xPositions].sort((a, b) => a - b));
			expect(new Set(xPositions).size).toBe(5);

			// No <image> ramp is drawn for a categorical scale.
			expect(container.querySelector('svg > image')).toBeNull();
		});

		it('renders one axis tick per threshold value', async () => {
			const { container } = render(ColorLegend, {
				color: bandColorScale,
				title: 'Age (years)'
			});

			const ticks = container.querySelectorAll('#ticks .tick');
			// scaleThreshold([22, 35, 51, 72], ...) has 4 thresholds.
			expect(ticks).toHaveLength(4);

			const tickLabels = Array.from(ticks).map((t) => t.textContent?.trim());
			expect(tickLabels).toEqual(['22', '35', '51', '72']);
		});
	});

	describe('ordinal scale', () => {
		it('renders one swatch rect per domain value, in domain order', async () => {
			const { container } = render(ColorLegend, { color: ordinalScale, title: 'Category' });

			const rects = container.querySelectorAll('svg > g > rect');
			expect(rects).toHaveLength(4);

			expect(rects[0]).toHaveAttribute('fill', '#c5dcf2');
			expect(rects[1]).toHaveAttribute('fill', '#8fb4db');
			expect(rects[2]).toHaveAttribute('fill', '#628dba');
			expect(rects[3]).toHaveAttribute('fill', '#3b6894');

			const xPositions = Array.from(rects).map((r) => Number(r.getAttribute('x')));
			expect(xPositions).toEqual([...xPositions].sort((a, b) => a - b));
			expect(new Set(xPositions).size).toBe(4);
		});
	});

	describe('continuous (sequential) scale', () => {
		it('renders a single color ramp image rather than discrete swatches', async () => {
			const { container } = render(ColorLegend, {
				color: sequentialScale,
				title: 'Temperature (°F)'
			});

			const images = container.querySelectorAll('svg > image');
			expect(images).toHaveLength(1);

			// No discrete swatch rects are drawn for a continuous scale.
			expect(container.querySelectorAll('svg > g > rect')).toHaveLength(0);
		});

		it('renders axis ticks generated by d3 for the scale', async () => {
			const { container } = render(ColorLegend, {
				color: sequentialScale,
				title: 'Temperature (°F)'
			});

			const ticks = container.querySelectorAll('#ticks .tick');
			expect(ticks.length).toBeGreaterThan(0);
		});

		it('respects explicit tickValues, rendering exactly those ticks in order', async () => {
			const { container } = render(ColorLegend, {
				color: sequentialScale,
				title: 'Temperature (°F)',
				tickValues: [0, 21, 42, 63, 84, 100]
			});

			const ticks = container.querySelectorAll('#ticks .tick');
			expect(ticks).toHaveLength(6);

			const tickLabels = Array.from(ticks).map((t) => t.textContent?.trim());
			expect(tickLabels).toEqual(['0', '21', '42', '63', '84', '100']);
		});
	});

	it('renders the title', async () => {
		render(ColorLegend, { color: ordinalScale, title: 'Category' });

		await expect.element(page.getByText('Category')).toBeInTheDocument();
	});

	it('renders leftLabel and rightLabel', async () => {
		render(ColorLegend, {
			color: bandColorScale,
			title: 'Age',
			leftLabel: 'Younger',
			rightLabel: 'Older'
		});

		await expect.element(page.getByText('Younger')).toBeInTheDocument();
		await expect.element(page.getByText('Older')).toBeInTheDocument();
	});

	it('only draws the highlight arrow when highlightedValue is set', async () => {
		const { container: withoutHighlight } = render(ColorLegend, {
			color: ordinalScale,
			title: 'Category'
		});
		expect(withoutHighlight.querySelector('svg > g > path')).toBeNull();

		const { container: withHighlight } = render(ColorLegend, {
			color: ordinalScale,
			title: 'Category',
			highlightedValue: 'B'
		});
		expect(withHighlight.querySelector('svg > g > path')).not.toBeNull();
	});

	// Note: the template has an `{#if !color}` branch that renders "Loading...", but the
	// `axisState` `$derived.by` (and the `$effect` that reads it) unconditionally accesses
	// `color.interpolate` etc. with no matching guard, so passing `color: undefined` throws
	// rather than rendering the loading message. That looks like a pre-existing bug in
	// ColorLegend.svelte, out of scope for these tests, so it is not exercised here.
});
