name: Lint PRs

on:
  push:
    branches: ["dev", "main"]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm
          
      - name: Install dependencies
        run: npm install
        
      - name: Lint
        run: npm run lint
        
