name: Publish Packages to NPM

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - normal
          - ds3

permissions:
  id-token: write # Required for OIDC
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: NPM publishing

    steps:
      - name: Checkout the git repository
        uses: actions/checkout@v6

      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v6
        with:
          node-version: '24.15.0'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false # never use caching in release builds

      - name: Install dependencies
        run: npm install

      - name: Install turbo
        run: npm install turbo --global

      - name: Publish packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: |
          if [ "${{ inputs.release_type }}" == "ds3" ]; then
            npm run publish-packages-ds3
          else
            npm run publish-packages
          fi

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          if [ "${{ inputs.release_type }}" == "ds3" ]; then
            git checkout -b release-msg-ds3
          else
            git checkout -b release-msg
          fi

          git add -A .changeset
          git add packages/*/CHANGELOG.md
          git add packages/*/package.json
          git add package-lock.json
          git reset HEAD .github/  # safety net

          git diff-index --quiet HEAD || git commit -m "Update CHANGELOG and package.json"

      - name: Push committed changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ inputs.release_type == 'ds3' && 'release-msg-ds3' || 'release-msg' }}
